//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCQ
    {
        public string MCQID { get; set; }
        public string MCQuestion { get; set; }
        public string Opt1 { get; set; }
        public string Opt2 { get; set; }
        public string Opt3 { get; set; }
        public string Opt4 { get; set; }
        public string COpt { get; set; }
        public string AssessmentCode { get; set; }
        public byte[] Img { get; set; }
    
        public virtual Assessment Assessment { get; set; }
    }
}
