//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakenAss
    {
        public string AssessmentCode { get; set; }
        public string StudID { get; set; }
        public Nullable<int> mark { get; set; }
        public string AssStatus { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual Student Student { get; set; }
    }
}
