//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrittenQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WrittenQuestion()
        {
            this.StudAns = new HashSet<StudAn>();
        }
    
        public string QuestionID { get; set; }
        public string Question { get; set; }
        public string AssessmentCode { get; set; }
        public byte[] SubImg { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudAn> StudAns { get; set; }
    }
}
